### ISSUE TITLE
Set unecessary color

### ISSUE THREAD

**Issue by GammaGames** [ryanolsonx/vscode-zenburn-theme#1]
I'm not sure if this is a new feature, but the default color is grey and blends in with regular text. I added this to my user settings:

```json
"workbench.colorCustomizations": {
    "editorUnnecessary.foreground": "#f5d5d1"
}
```

It sets it to a more noticable red-tint (`#f5d5d1`), though I do also like `#8e8e8e`.

Do you think you'll set the value in the theme?

**Comment by ryanolsonx** [comment]
This sounds like a great addition. I'll include it soon and make a new release. Thanks! :+1:

**Comment by GammaGames** [comment]
Is there any ETA for this?

Also I've moved to using `#8e8e8e` all the time now, I think dimming it makes more sense given the context of unused.

**Comment by ryanolsonx** [comment]
I’ll do this tomorrow. Sorry for the delay. 👍😀

**Comment by ryanolsonx** [comment]
Done.
