### ISSUE TITLE
Completions are not themed

### ISSUE THREAD

**Issue by carlbolduc** [ryanolsonx/vscode-zenburn-theme#2]
When completions appear, they seem to be using the default dark theme:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/410440/50036211-30676700-ffd5-11e8-9342-9d5b965f03fd.png">

**Comment by ryanolsonx** [comment]
Nice catch. I’ll dig into theming the completions some time soon.

**Comment by ryanolsonx** [comment]
Done! 🎉  Please let me know if there's anything else missing.
