### ISSUE TITLE
Breadcrumbs are not themed

### ISSUE THREAD

**Issue by GammaGames** [ryanolsonx/vscode-zenburn-theme#3]
Related to #2, the breadcrumbs background is the default background color: 

![image](https://user-images.githubusercontent.com/7832163/50357279-a3f7ff80-0512-11e9-90fe-0be703ee9e4b.png)

**Comment by ryanolsonx** [comment]
Nice find! I'll fix it when I get the time. PRs welcome.

**Comment by GammaGames** [comment]
There's a bunch of widget styles that look like they might be inherited, the following rules seemed to make the search input and breadcrumb panel match better:

```json
"editorWidget.background": "#2c2e2e",
"editorWidget.border": "#9f9f9f",
"editorMarkerNavigation.background": "#2c2e2e"
```
